# Generated by Django 4.0.6 on 2022-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
